export const Images = {
  ic_arrow_back: require('@assets/images/ic_arrow_back.png'),
  ic_booking_success: require('@assets/images/ic_booking_success.png'),
  ic_calendar: require('@assets/images/ic_calendar.png'),
  ic_car: require('@assets/images/ic_car.png'),
  ic_chevron_back: require('@assets/images/ic_chevron_back.png'),
  ic_fix_car: require('@assets/images/ic_fix_car.png'),
  ic_left_chevron: require('@assets/images/ic_left_chevron.png'),
  ic_location: require('@assets/images/ic_location.png'),
  ic_marker: require('@assets/images/ic_marker.png'),
  ic_pickup_car: require('@assets/images/ic_pickup_car.png'),
  ic_progress_1: require('@assets/images/ic_progress_1.png'),
  ic_progress_2: require('@assets/images/ic_progress_2.png'),
  ic_progress_3: require('@assets/images/ic_progress_3.png'),
  ic_progress_4: require('@assets/images/ic_progress_4.png'),
  ic_progress_5: require('@assets/images/ic_progress_5.png'),
  ic_progress_6: require('@assets/images/ic_progress_6.png'),
  ic_repair_car: require('@assets/images/ic_repair_car.png'),
  ic_right_chevron: require('@assets/images/ic_right_chevron.png'),
  ic_search: require('@assets/images/ic_search.png'),
  ic_selected: require('@assets/images/ic_selected.png'),
  ic_swipe_car: require('@assets/images/ic_swipe_car.png'),
  ic_switch_close: require('@assets/images/ic_switch_close.png'),
};
